"""updated types for models 

Revision ID: 2380a92db229
Revises: 8adb637ce892
Create Date: 2026-02-24 09:58:29.772621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2380a92db229'
down_revision: Union[str, Sequence[str], None] = '8adb637ce892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_processing_tasks', sa.Column('status', sa.String(length=255), nullable=False))
    op.alter_column('document_processing_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_processing_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('document_processing_tasks', 'status')
    # ### end Alembic commands ###
