"""updated nullability on documents

Revision ID: 8adb637ce892
Revises: dc0b77d22748
Create Date: 2026-02-21 14:54:38.210673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adb637ce892'
down_revision: Union[str, Sequence[str], None] = 'dc0b77d22748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
