"""updated document processing task

Revision ID: ce41e014ffab
Revises: 8e9a0e7fa12f
Create Date: 2026-02-21 13:22:14.181123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce41e014ffab'
down_revision: Union[str, Sequence[str], None] = '8e9a0e7fa12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_processing_tasks', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('document_processing_tasks', 'error',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('idx_document_processing_tasks_created_at', 'document_processing_tasks', ['created_at'], unique=False)
    op.create_index('idx_document_processing_tasks_document_id', 'document_processing_tasks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_processing_tasks_document_id', table_name='document_processing_tasks')
    op.drop_index('idx_document_processing_tasks_created_at', table_name='document_processing_tasks')
    op.alter_column('document_processing_tasks', 'error',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_processing_tasks', 'result',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
